name: Build

on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize
      - reopened
jobs:
  reusable_job:
    uses: mattsmith47988/.github/.github/workflows/reusable_demo.yaml@main